// src/components/_global/BalCard/BalCard.jsx
import React from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';

const BalCard = ({ className, title, titleTag, square, noPad, noContentPad, noBorder, darkBgColor, shadow, children, header, footer }) => {
  const headerClasses = classNames('header flex items-center', {
    'p-4 pb-3': !noPad
  });

  const contentClasses = classNames('content', {
    'p-4 pt-3': !noPad && !noContentPad
  });

  const footerClasses = classNames('footer flex items-center bg-gray-50 dark:bg-gray-850 border-t border-gray-100 dark:border-gray-900', {
    'rounded-b-lg': !square,
    'p-4 pt-3': !noPad
  });

  const componentClasses = classNames('bal-card', {
    'rounded-lg': !square,
    [`bg-white dark:bg-gray-${darkBgColor}`]: darkBgColor,
    [`shadow${shadow ? '-' : ''}${shadow}`]: shadow,
    'border dark:border-gray-900': !noBorder
  }, className);

  const HeaderComponent = header;
  const FooterComponent = footer;
  const TitleComponent = titleTag;

  return (
    <div className={componentClasses}>
      {
        (title || header) && (
          <div className={headerClasses}>
            {
              title && (
                <TitleComponent>{title}</TitleComponent>
              )
            }
            {
              header && (
                <div className="flex-1 flex items-center">
                  <HeaderComponent />
                </div>
              )
            }
          </div>
        )
      }
      <div className={contentClasses}>
        {children}
      </div>
      {
        footer && (
          <div className={footerClasses}>
            <FooterComponent />
          </div>
        )
      }
    </div>
  )
}

BalCard.propTypes = {
  className: PropTypes.string,
  title: PropTypes.string,
  titleTag: PropTypes.string,
  square: PropTypes.bool,
  noPad: PropTypes.bool,
  noContentPad: PropTypes.bool,
  noBorder: PropTypes.bool,
  darkBgColor: PropTypes.string,
  shadow: PropTypes.oneOf(['', 'none', 'sm', 'md', 'lg', 'xl']),
  children: PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.node),
    PropTypes.node
  ]),
  header: PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.node),
    PropTypes.node
  ]),
  footer: PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.node),
    PropTypes.node
  ])
};

BalCard.defaultProps = {
  className: '',
  title: '',
  titleTag: 'h5',
  square: false,
  noPad: false,
  noContentPad: false,
  noBorder: false,
  darkBgColor: '850',
  shadow: '',
  children: null,
  header: null,
  footer: null,
};

export default BalCard;

// src/components/_global/BalCard/BalCard.vue
  <template>
  <div :class="['bal-card', cardClasses]">
    <div v-if="!!title || $slots.header" :class="['header', headerClasses]">
      <component :is="titleTag" v-if="!!title" v-text="title" />
      <div v-if="$slots.header" class="flex-1 flex items-center">
        <slot name="header" />
      </div>
    </div>
    <div :class="['content', contentClasses]">
      <slot />
    </div>
    <div v-if="$slots.footer" :class="['footer', footerClasses]">
      <slot name="footer" />
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, computed } from 'vue';

export default defineComponent({
  name: 'BalCard',

  props: {
    title: { type: String, default: '' },
    titleTag: { type: String, default: 'h5' },
    square: { type: Boolean, default: false },
    noPad: { type: Boolean, default: false },
    noContentPad: { type: Boolean, default: false },
    noBorder: { type: Boolean, default: false },
    darkBgColor: { type: String, default: '850' },
    shadow: {
      type: String,
      default: '',
      validator: (val: string): boolean => {
        return ['', 'none', 'sm', 'md', 'lg', 'xl'].includes(val);
      }
    }
  },

  setup(props) {
    const borderClasses = computed(() => {
      return 'border dark:border-gray-900';
    });

    const cardClasses = computed(() => {
      return {
        'rounded-lg': !props.square,
        [`bg-white dark:bg-gray-${props.darkBgColor}`]: true,
        [`shadow${props.shadow ? '-' : ''}${props.shadow}`]: true,
        [borderClasses.value]: !props.noBorder
      };
    });

    const headerClasses = computed(() => {
      return {
        'p-4 pb-3': !props.noPad
      };
    });

    const contentClasses = computed(() => {
      return {
        'p-4 pt-3': !props.noPad && !props.noContentPad
      };
    });

    const footerClasses = computed(() => {
      return {
        'rounded-b-lg': !props.square,
        'p-4 pt-3': !props.noPad
      };
    });

    return {
      cardClasses,
      contentClasses,
      headerClasses,
      footerClasses
    };
  }
});
</script>

<style scoped>
.header {
  @apply flex items-center;
}

.footer {
  @apply flex items-center;
  @apply bg-gray-50 dark:bg-gray-850;
  @apply border-t border-gray-100 dark:border-gray-900;
}
</style>
